scss_files: 'app/**/*.scss'

exclude: 'app/**.tmplt.scss'

linters:
    Indentation:
        severity: error
        width: 4

    NestingDepth:
        enabled: true
        max_depth: 5
        ignore_parent_selectors: false

    SelectorDepth:
        enabled: true
        max_depth: 5

    ImportantRule:
       enabled: false

    IdSelector:
       enabled: false